# Generated by Django 4.2.6 on 2023-12-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='measure',
            new_name='unit',
        ),
    ]
