# Generated by Django 4.2.6 on 2024-01-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='show_template',
            field=models.CharField(default='', max_length=400),
        ),
    ]
