# Generated by Django 4.2.6 on 2024-01-09 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_achievementlist_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
