# Generated by Django 4.2.6 on 2024-04-24 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_recommender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommender',
            name='day',
        ),
        migrations.AddField(
            model_name='recommender',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
